name: Monthly Data Extraction

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 on the first day of each month
    - cron: "0 0 15 * *" # Runs at 00:00 on the 15th day of each month
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  data-transformation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Install NPM dependencies
      run: |
        cd node
        npm install
    - name: Create data directories
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
    - name: Run Prefect Flow
      run: |
        python main.py
    - name: Commit processed data
      run: |
        git config --local user.email "
        git config --local user.name "
        git add data/processed/*
        # Use the current date as the commit message
        git commit -m "Update processed data $(date -I)"
        git push
    - name: Remove raw data
      run: |
        rm -rf data/raw/*
